# Generated by Django 5.1.2 on 2024-10-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_first_app",
            "0002_rename_auto_car_rename_id_auto_ownership_id_car_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="cars",
            field=models.ManyToManyField(
                through="project_first_app.Ownership", to="project_first_app.car"
            ),
        ),
    ]
